"""Bake ground-level collision from the shipped USDZ; no device mesh cooking.
Requires numpy and usd-core. Run AFTER build_castle_from_glb.py.
The current locomotion is planar: ground/courtyard only, not towers or stairs.
"""
from pathlib import Path
import hashlib, json, math
import numpy as np
from pxr import Usd, UsdGeom
ROOT=Path(__file__).resolve().parents[1]
FLOOR=4.72; CELL=.2; X0=-27.; Z0=-20.
GATE_X=-2.55; SPAWN_Z=-6.5
heights=np.zeros((205,270),dtype=np.int16)

def clip(poly, level, above):
    out=[]
    for a,b in zip(poly,poly[1:]+poly[:1]):
        ia=(a[1]>=level) if above else (a[1]<=level)
        ib=(b[1]>=level) if above else (b[1]<=level)
        if ia:out.append(a)
        if ia!=ib:out.append(a+(b-a)*((level-a[1])/(b[1]-a[1])))
    return out

stage=Usd.Stage.Open(str(ROOT/'Resources/Castle.usdz'))
for prim in stage.Traverse():
    if not prim.IsA(UsdGeom.Mesh):continue
    mesh=UsdGeom.Mesh(prim);p=np.array(mesh.GetPointsAttr().Get())
    faces=np.array(mesh.GetFaceVertexIndicesAttr().Get()).reshape(-1,3)
    # Height is conservative for each source piece; footprint is triangle-derived.
    height=max(1,math.ceil((p[:,1].max()-FLOOR)*2))
    tris=p[faces];tris=tris[(tris[:,:,1].min(1)<FLOOR+1.45)&(tris[:,:,1].max(1)>FLOOR+.35)]
    for tri in tris:
        poly=clip(clip(list(tri),FLOOR+.35,True),FLOOR+1.45,False)
        if len(poly)<3:continue
        v=np.array(poly)[:,[0,2]]
        lower=np.floor((v.min(0)-[X0,Z0])/CELL).astype(int)
        upper=np.floor((v.max(0)-[X0,Z0])/CELL).astype(int)
        lower=np.maximum(lower,0);upper=np.minimum(upper,[269,204])
        xs=np.arange(lower[0],upper[0]+1);zs=np.arange(lower[1],upper[1]+1)
        xx,zz=np.meshgrid(xs,zs);centers=np.stack([X0+(xx+.5)*CELL,Z0+(zz+.5)*CELL],axis=-1)
        overlap=np.ones(xx.shape,dtype=bool)
        # Convex polygon versus grid squares by separating axes; also handles
        # projected vertical faces (zero-area line segments).
        edges=np.roll(v,-1,axis=0)-v
        for axis in np.concatenate([np.eye(2),np.stack([-edges[:,1],edges[:,0]],axis=1)]):
            if np.linalg.norm(axis)<1e-8:continue
            values=v@axis;c=centers@axis;r=CELL/2*np.abs(axis).sum()
            overlap &= (c+r>=values.min()-1e-6)&(c-r<=values.max()+1e-6)
        current=heights[zz,xx]
        heights[zz,xx]=np.where(overlap,np.maximum(current,height),current)

# Merge matching occupied runs vertically, retaining their maximum height.
# Only height is conservative; empty doorway cells are never filled.
rects=[];active={}
for z,row in enumerate(heights):
    runs=[];x=0
    while x<len(row):
        if row[x]==0:x+=1;continue
        start=x;h=int(row[x])
        while x<len(row) and row[x]>0:x+=1
        h=int(row[start:x].max())
        runs.append((start,x,h))
    new={}
    for a,b,h in runs:
        key=(a,b)
        if key in active:new[key]=active.pop(key)
        else:new[key]=[a,b,z,z+1,h]
        new[key][3]=z+1
        new[key][4]=max(new[key][4],h)
    rects.extend(active.values());active=new
rects.extend(active.values())
boxes=[]
for a,b,c,d,h in rects:
    boxes.append([round(X0+a*CELL,4),round(Z0+c*CELL,4),round(X0+b*CELL,4),round(Z0+d*CELL,4),h/2])
# Shared generated poses prevent the visual model, collision and spawn diverging.
lines=['// Generated by Tools/build_castle_navigation.py from Resources/Castle.usdz.',
       '// Ground-level collision only; do not manually edit.', 'enum CastleLayout {',
       f'    static let courtyardHeight: Float = {FLOOR}',
       f'    static let gateX: Float = {GATE_X}',
       f'    static let spawnZ: Float = {SPAWN_Z}',
       '    // min X, min Z, max X, max Z, obstacle height in asset-local coordinates.',
       '    static let boxes: [[Float]] = {', '        var result: [[Float]] = []']
for start in range(0,len(boxes),40):
    lines.append('        result += [')
    lines += ['            ['+', '.join(str(n) for n in r)+'],' for r in boxes[start:start+40]]
    lines.append('        ]')
lines+=['        return result','    }()','}','']
(ROOT/'Game/CastleLayout.swift').write_text('\n'.join(lines))
report={'runtime_sha256':hashlib.sha256((ROOT/'Resources/Castle.usdz').read_bytes()).hexdigest(),
        'courtyard_height':FLOOR,'cell_size':CELL,'body_height_slab':[.35,1.45],
        'gate_x':GATE_X,'spawn_z':SPAWN_Z,'rectangles':len(boxes),'boxes':boxes}
(ROOT/'SourceAssets/castle-navigation.json').write_text(json.dumps(report,separators=(',',':'))+'\n')
print('collision rectangles per castle:',len(boxes))
